function changePara1() {
 let text = "This is modified para 1";
 document.getElementById('pId1').innerHTML = text;   
}
function changePara2() {
 let text = "This is modified para 2";
 document.getElementById('pId2').innerHTML = text;   
}
function changePara3() {
 let text = "This is modified para 3";
 document.getElementById('pId3').innerHTML = text;   
}
function changePara4() {
 let text = "This is modified para 4";
 document.getElementById('pId4').innerHTML = text;   
}